"""Update WaterSource for notifications

Revision ID: 4f6768317505
Revises: 3af610f888a7
Create Date: 2026-05-20 22:53:42.945420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6768317505'
down_revision = '3af610f888a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('committee_phone', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_sources', schema=None) as batch_op:
        batch_op.drop_column('preferred_language')
        batch_op.drop_column('committee_phone')

    # ### end Alembic commands ###
